### PR TITLE
Fix: Depend on MixinExtras properly.

### PR DESCRIPTION
**Pull request by LlamaLad7**
As mentioned in [the release notes](https://github.com/LlamaLad7/MixinExtras/releases/tag/0.2.0-beta.6), you need to depend on MixinExtras differently since `0.2.0-beta.5`. The MixinExtras jar included in your latest release is empty, causing https://github.com/LlamaLad7/MixinExtras/issues/28.

### CODE REVIEW

**Comment by chronosacaria** [comment]
@LlamaLad7 Ohhhhh. Wow I really derped on this one. Thanks for explaining this to me. I'll merge the pull request and get that fix taken care of. Thank you again!

**Comment by LlamaLad7** [comment]
I forgot about that as well ^

**Comment by chronosacaria** [comment]
Hey, @LlamaLad7! I am running into some issues with the new version of Mixin Extras (at least, I think that's what happening). There is now a conflict with MemoryLeakFix and MCDW that is producing the following error: [latest.log](https://github.com/chronosacaria/MCDungeonsWeapons/files/11500338/latest.log)

We managed to chase down the issue being linked to [this mixin](https://github.com/fxmorin/MemoryLeakFix/blob/dev/common/src/main/java/ca/fxco/memoryleakfix/mixin/hugeScreenshotLeak/Minecraft_screenshotMixin.java#L25) in MemoryLeakFix, but I am not sure if this is something that is being caused by Mixin Extras or if this is something that either of us need to fix on our end. We don't touch the same methods in MCDW, so I am unsure of how it could be something that we're doing. If you could offer any insight, that would be amazing!

Thanks, in advance!

**Comment by LlamaLad7** [comment]
Yep, my bad, fixed in beta 8. Sorry for the inconvenience, I broke something while fixing something else.

**Comment by chronosacaria** [comment]
@LlamaLad7 Ah, thank you, so much!

**Pull request merged**
